#!/usr/bin/env python3

import configparser
import logging
import os
import sys
import time
from collections.abc import Iterator

DEFAULT_CONFIGFILE = "/etc/rockpro-fan.conf"

logger = logging.getLogger(__name__)

handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)


class FanController:
    def __init__(self, configfile=DEFAULT_CONFIGFILE):
        self._configfile = configfile
        self.config = self._load_config()
        self.previously_set_speed = -1
        logger.setLevel(int(self.config['LoggingLevel']))

    def _load_config(self) -> configparser.SectionProxy:
        config = configparser.ConfigParser()
        with open(self._configfile, encoding="utf8") as stream:
            config.read_string("[top]\n" + stream.read())
        return config["top"]

    def run(self) -> None:
        while True:
            temp = self._get_temperature()
            logger.debug("CPU temperature: %s °C", temp)
            speed = self._determine_speed_percentage(temp)
            self._set_fan_speed(speed)
            self._sleep()

    def _get_temperature(self) -> float:
        with open(self.config["TemperatureFile"], "r", encoding="utf8") as f:
            return int(f.read()) / 1000

    def _determine_speed_percentage(self, temp: float) -> float:
        low = float(self.config["LowSpeedTemperature"])
        high = float(self.config["HighSpeedTemperature"])

        percentage = (temp - low) / (high - low)
        # Return percentage if it's between 0 and 1
        return min(max(0, percentage), 1)

    def _set_fan_speed(self, speed_percentage: float) -> None:
        assert speed_percentage >= 0, "Speed percentage should be positive"
        assert speed_percentage <= 1, "Speed percentage cannot exceed 1"

        speed_integer = self._determine_speed_integer(speed_percentage)

        if speed_integer == self.previously_set_speed:
            logger.debug("Not setting speed again - same as last time")
            return

        self._set_pwm(speed_integer)
        self.previously_set_speed = speed_integer

    def _determine_speed_integer(self, speed_percentage: float) -> int:
        low = int(self.config["FanPWMLow"])
        high = int(self.config["FanPWMHigh"])
        assert high >= low, "FanPWMHigh should be higher than FanPWMLow"

        difference = high - low
        extra = speed_percentage * difference
        return round(extra + low)

    def _set_pwm(self, speed: int) -> None:
        valid_devices = self._get_existing_device_filenames()
        for device in valid_devices:
            self._set_pwm_of_device(device, speed)

    def _get_existing_device_filenames(self) -> Iterator[str]:
        hardcoded_hwmon_max_amount = 16
        hardcoded_hwmon_path = "/sys/devices/platform/pwm-fan/hwmon/hwmon{id}/pwm1"

        for hwmon_id in range(hardcoded_hwmon_max_amount):
            filename = hardcoded_hwmon_path.format(id=hwmon_id)
            if os.path.exists(filename):
                yield filename

    def _set_pwm_of_device(self, filename: str, speed: int) -> None:
        logger.info("Writing %s to %s", speed, filename)
        with open(filename, "w", encoding="utf8") as f:
            f.write(str(speed))

    def _sleep(self) -> None:
        time.sleep(int(self.config["SleepSeconds"]))


def main():
    fancontroller = FanController()
    fancontroller.run()


if __name__ == "__main__":
    main()
